#!/bin/bash

DIR=/tmp/zabbix_updatecount
source /etc/os-release

function set_crontab() {
    mkdir $DIR
    case $ID in
        fedora|rhel)
            (crontab -l 2>/dev/null; echo "0 0 * * * dnf check-update | grep -Ec ' *updates' > $DIR/upgrade_count") | crontab -
            echo "Crontab has been added! check update crontab will run every night at 12.00AM"
        ;;
        debian|ubuntu)
            (crontab -l 2>/dev/null; echo "0 0 * * * apt update && apt list --upgradable | grep -Ec ' upgradable' > $DIR/upgrade_count") | crontab -
            echo "Crontab has been added! check update crontab will run every night at 12.00AM"        
        ;;
    esac
}

function getupdates() {
    if [ ! -f $DIR ]; then
        test -f $file/upgrade_count || { echo "Upgrades have not been checked yet" > $file/upgrade_count; ok=0; }
    fi
    cd $DIR
    echo $DIR/upgrade_count
}

action=$1

case "$action" in
    *--set-crontab*)
        set_crontab
        ;;
    *--get-updates*)
        getupdates
        ;;
    *updates.upgrade_count*)
        test -f $DIR/upgrade_count && cat $DIR/upgrade_count
        ;;
        *)
    echo "ERROR: Usage is getupdates --set-crontab to set the crontab or getupdates --get-updates to manually run the poll"
        ;;
esac
