#!/bin/bash

DIR=/tmp

function getupdates() {
    if [ ! -f $DIR ]; then
        test -f $file/upgrade_count || { echo "Upgrades have not been checked yet" > $file/upgrade_count; ok=0; }
    fi
    cd $DIR
    echo $DIR/upgrade_count
}

function pre-flights() {
    ok=1
    for file in $DIR
    do
        test -f $file/upgrade_count || { echo "Upgrades have not been checked yet" > $file/upgrade_count; ok=0; }
    done
}

pre-flights

action=$1

case "$action" in
    getupdates)
        getupdates
        ;;
    updates.upgrade_count)
        test -f $DIR/upgrade_count && cat $DIR/upgrade_count
        ;;
esac
